default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  password: "qweqweqwe"

development:
  <<: *default
  database: blogdhh_development

test:
  <<: *default
  database: blogdhh_test

production:
  <<: *default
  database: blogdhh_production
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>
